"""UI for demos. This UI has been fully generated by gemini-3-flash."""

import gc
import json
import subprocess

import PIL.Image
import requests
import streamlit as st

from delt import AudioPipeline, ImagePipeline, TextPipeline, VideoPipeline

# -----------------------------------------------------------------------------
# Configuration & Page Setup
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="DELT Playground",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom Styling for a modern UI
st.markdown(
    """
    <style>
    .main .block-container { padding-top: 2rem; }
    .stTabs [data-baseweb="tab-list"] { gap: 10px; }
    .stTabs [data-baseweb="tab"] {
        padding: 8px 16px;
        background-color: #f0f2f6;
        border-radius: 4px;
        font-weight: 600;
    }
    .stTabs [aria-selected="true"] { 
        background-color: #ff4b4b !important;
        color: white !important;
    }
    div.stButton > button:first-child {
        width: 100%;
    }
    /* Style for the stakeholder box */
    .stakeholder-box {
        background-color: #f8f9fa;
        border-left: 5px solid #007bff;
        padding: 1.5rem;
        border-radius: 4px;
        margin-bottom: 2rem;
    }
    </style>
""",
    unsafe_allow_html=True,
)

st.title("🚀 DELT Playground")
st.markdown(
    "Explore **Zero-Shot Classification** and **Label-Tuning** as two complementary pathways for evaluating and training multi-modal models."
)

# -----------------------------------------------------------------------------
# Stakeholder Explanation Box
# -----------------------------------------------------------------------------
with st.expander(
    "💼 If you are asking `what is this?`, click here to expand an explanation.",
    expanded=False,
):
    st.markdown(
        """
        ### 📊 System Capabilities
        This library is designed to train, run predictions, and evaluate dual-encoder models across **text, image, audio, and video data**. It supports two main modes:
        * **Zero-Shot Mode:** The system uses pre-trained embeddings to perform classification **out of the box** without requiring any training data.
        * **Label-Tuned Mode:** The model is adapted using a small amount of labeled data, making it especially effective in few-shot or low-data scenarios. While it can scale up, it is primarily optimized for situations where labeled data is limited or unavailable.
        
        ---
        
        ### 🧠 What is Label Tuning?
        Label tuning works by learning meaningful representations of the class labels themselves. Instead of training a massive classifier from scratch, the model learns to align inputs with natural language descriptions of labels.
        
        > **Example:** Given the sentence *"I love this film"* and the label *"positive"*, the model learns to map the embedding of the sentence closer to the embedding of a phrase like *"This review is positive"*.
        
        Technically, it only adds a small classification layer (with parameters proportional to the number of labels x embedding size). This architectural design yields significant production benefits:
        1. **Lightweight Infrastructure:** The massive underlying embedding models can remain unchanged and hosted remotely.
        2. **CPU-Friendly:** The label-tuning layer runs efficiently on a CPU, unlocking ultra-fast training and inference loops.
        
        *For more technical details, see the original paper: [arXiv:2203.14655](https://arxiv.org/pdf/2203.14655)*
        
        **As long as we have embedding models deployed in GPUs (with a proper caching strategy) and accessible through an API, label tuning and inference can be done extremely fast in CPU, since the embedding model remains untouched.**

        ---
        
        ### 🎯 Why This Matters & Where It Is Useful
        
        ##### **Core Business Value**
        * **Zero/Few-Shot Efficiency:** Drastically reduces dependencies on massive labeled datasets.
        * **Rapid Time-to-Market:** Fast deployment cycles without retraining heavy foundation models.
        * **True Multimodality:** Unified approach across text, image, audio, and video domains.
        * **Cost-Effective Scalability:** Drastically reduces cloud computing bills by keeping infrastructure lightweight.
        
        ##### **Typical Production Use Cases**
        * **Content Classification:** Sentiment tracking, automated topic tagging, and trust/safety moderation.
        * **Search & Discovery:** Semantic recommendation and search engines.
        * **Multimodal Retrieval:** Seamless cross-matching (e.g., matching text $\leftrightarrow$ image $\leftrightarrow$ audio $\leftrightarrow$ video).
        * **Rapid Prototyping:** Validating machine learning features quickly without spun-up training pipelines.
        """
    )

with st.expander(
    "</> If you are asking `how can I use this outside this UI?` click here to expand an explanation.",
    expanded=False,
):
    st.markdown(r"""
    Just clone the repo `https://tfs.transperfect.com/tfs/Machine Translation/AI R and D/_git/few-shot-classification` and follow the README.

    The pipelines are simple:

    ```python
    from delt import TextPipeline

    # Instantiate the pipeline
    pipeline = TextPipeline(
        encoder_name="sentence-transformers/all-MiniLM-L6-v2",
        encoder_class="sentence-transformer",
        label_verbalizations={
            "positive": "really positive",
            "negative": "really negative",
        },
        prompt_template="This text is {}",
    )

    # Define your data
    texts = ["I'm happy", "I'm sad"]
    truths = [0, 1, 0, 1]

    # Zero-shot
    predictions = pipeline.predict(texts)

    # Few-shot label tuning
    pipeline.train(texts, labels)

    # Predict again
    predictions = pipeline.predict(texts)```""")
st.write("---")


# Helper function to stream download youtube video bytes
def download_youtube_video(url: str) -> bytes:
    """
    Download a video from Youtube.

    Args:
        url (str): the url of the video.

    Returns:
        bytes: the video as bytes.

    """
    result = subprocess.run(
        [
            "yt-dlp",
            "-f",
            "worst[ext=mp4]",
            "-o",
            "-",
            url,
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return result.stdout


# -----------------------------------------------------------------------------
# Modality Tabs
# -----------------------------------------------------------------------------
tab_text, tab_image, tab_audio, tab_video = st.tabs(
    [
        "📝 Text Classification",
        "🖼️ Image Classification",
        "🎵 Audio Classification",
        "📹 Video Classification",
    ]
)

with tab_text:
    st.header("Text Classification")

    col1, col2 = st.columns([1, 2], gap="large")

    with col1:
        st.subheader("Configuration")
        encoder_name_t = st.text_input(
            "Encoder Name",
            "sentence-transformers/all-MiniLM-L6-v2",
            key="en_t",
            disabled=True,
        )
        encoder_class_t = st.text_input(
            "Encoder Class", "sentence-transformer", key="ec_t", disabled=True
        )
        prompt_template_t = st.text_input(
            "Prompt Template", "This text is {}", key="pt_t"
        )

        st.markdown("**Label Verbalizations (JSON format)**")
        labels_input_t = st.text_area(
            "Labels mapping",
            '{\n  "positive": "really positive",\n  "negative": "really negative"\n}',
            height=100,
            key="lbl_t",
        )

        st.markdown("**Data Inputs**")
        texts_input = st.text_area(
            "Texts (one per line)",
            "I'm happy\nI'm sad\nYou're strong\nFuck you.",
            height=120,
        )
        truths_input_t = st.text_input(
            "Ground Truth Labels (Indices for Training)", "0, 1, 0, 1"
        )

        run_text = st.button("🚀 Run Text Pipelines", type="primary")

    with col2:
        st.subheader("Execution & Results")
        if run_text:
            with st.spinner("Processing Text Pipeline..."):
                try:
                    label_verbalizations = json.loads(labels_input_t)
                    texts = [
                        t.strip() for t in texts_input.split("\n") if t.strip()
                    ]
                    truths = [
                        int(x.strip()) for x in truths_input_t.split(",")
                    ]

                    # Base Initialization
                    pipeline = TextPipeline(
                        encoder_name_t,
                        encoder_class_t,
                        label_verbalizations,
                        prompt_template_t,
                    )

                    # Pathway A: Zero-Shot
                    st.markdown("### 🎛️ Pathway A: Zero-Shot Predictions")
                    st.caption(
                        "Evaluating the model out-of-the-box without any additional training."
                    )
                    preds_zero = pipeline.predict(texts, batch_size=8)

                    for text, pred in zip(texts, preds_zero):
                        st.info(
                            f"**Text:** '{text}' ➔ **Prediction:** `{pred}`"
                        )

                    st.write("---")

                    # Pathway B: Label-Tuning
                    st.markdown("### 🏋️ Pathway B: Label-Tuning Fine-Tuning")
                    st.caption(
                        "Adapting the model's classification space using your provided ground truths."
                    )

                    with st.status(
                        "Training via label-tuning...", expanded=True
                    ) as status:
                        pipeline.fit(texts, truths)
                        status.update(
                            label="Fine-tuning complete!",
                            state="complete",
                            expanded=False,
                        )

                    preds_post = pipeline.predict(texts, batch_size=8)
                    for text, pred in zip(texts, preds_post):
                        st.success(
                            f"**Text:** '{text}' ➔ **Post-Training Prediction:** `{pred}`"
                        )

                except Exception as e:
                    st.error(f"An error occurred: {e}")
        else:
            st.info(
                "Configure the options on the left and click 'Run Text Pipelines'."
            )

# -----------------------------------------------------------------------------
# Tab 2: Image Classification
# -----------------------------------------------------------------------------
with tab_image:
    st.header("Image Classification")

    col1, col2 = st.columns([1, 2], gap="large")

    with col1:
        st.subheader("Configuration")
        encoder_name_i = st.text_input(
            "Encoder Name",
            "openai/clip-vit-base-patch32",
            key="en_i",
            disabled=True,
        )
        encoder_class_i = st.text_input(
            "Encoder Class", "clip", key="ec_i", disabled=True
        )
        prompt_template_i = st.text_input(
            "Prompt Template", "The animal in the image is a {}", key="pt_i"
        )

        st.markdown("**Label Verbalizations (JSON format)**")
        labels_input_i = st.text_area(
            "Labels mapping",
            '{\n  "cat": "cat",\n  "dog": "dog"\n}',
            height=100,
            key="lbl_i",
        )

        st.markdown("**Image Source URLs (one per line)**")
        urls_input = st.text_area(
            "URLs",
            "http://images.cocodataset.org/val2017/000000039769.jpg\nhttps://pngfre.com/wp-content/uploads/dog-poster.png",
            height=100,
        )
        truths_input_i = st.text_input(
            "Ground Truth Labels (Indices for Training)", "0, 1", key="tr_i"
        )

        run_image = st.button("🚀 Run Image Pipelines", type="primary")

    with col2:
        st.subheader("Execution & Results")
        if run_image:
            with st.spinner("Downloading images and processing pipeline..."):
                try:
                    label_verbalizations = json.loads(labels_input_i)
                    urls = [
                        u.strip() for u in urls_input.split("\n") if u.strip()
                    ]
                    truths = [
                        int(x.strip()) for x in truths_input_i.split(",")
                    ]

                    images = []
                    for url in urls:
                        img = PIL.Image.open(
                            requests.get(url, stream=True).raw
                        ).convert("RGB")
                        images.append(img)

                    st.markdown("### 📷 Input Preview")
                    grid = st.columns(len(images))
                    for idx, img in enumerate(images):
                        grid[idx].image(
                            img,
                            caption=f"Image Index {idx}",
                            use_container_width=True,
                        )

                    pipeline = ImagePipeline(
                        encoder_name_i,
                        encoder_class_i,
                        label_verbalizations,
                        prompt_template_i,
                    )

                    # Pathway A: Zero-Shot
                    st.markdown("### 🎛️ Pathway A: Zero-Shot Predictions")
                    st.caption(
                        "Evaluating the model out-of-the-box without any additional training."
                    )
                    preds_zero = pipeline.predict(images, batch_size=8)
                    for idx, pred in enumerate(preds_zero):
                        st.info(f"**Image {idx}** ➔ **Prediction:** `{pred}`")

                    st.write("---")

                    # Pathway B: Label-Tuning
                    st.markdown("### 🏋️ Pathway B: Label-Tuning Fine-Tuning")
                    st.caption(
                        "Adapting the model's classification space using your provided ground truths."
                    )

                    with st.status(
                        "Training via label-tuning...", expanded=True
                    ) as status:
                        pipeline.fit(images, truths)
                        status.update(
                            label="Fine-tuning complete!",
                            state="complete",
                            expanded=False,
                        )

                    preds_post = pipeline.predict(images, batch_size=8)
                    for idx, pred in enumerate(preds_post):
                        st.success(
                            f"**Image {idx}** ➔ **Post-Training Prediction:** `{pred}`"
                        )
                    try:
                        del images
                        del preds_zero
                        del preds_post
                        gc.collect()
                    except Exception:
                        pass
                except Exception as e:
                    st.error(f"An error occurred: {e}")
        else:
            st.info(
                "Configure the options on the left and click 'Run Image Pipelines'."
            )

# -----------------------------------------------------------------------------
# Tab 3: Audio Classification
# -----------------------------------------------------------------------------
with tab_audio:
    st.header("Audio Classification")

    col1, col2 = st.columns([1, 2], gap="large")

    with col1:
        st.subheader("Configuration")
        encoder_name_a = st.text_input(
            "Encoder Name",
            "laion/larger_clap_music_and_speech",
            key="en_a",
            disabled=True,
        )
        encoder_class_a = st.text_input(
            "Encoder Class", "clap", key="ec_a", disabled=True
        )
        prompt_template_a = st.text_input(
            "Prompt Template", "That sound is a {}", key="pt_a"
        )

        st.markdown("**Label Verbalizations (JSON format)**")
        labels_input_a = st.text_area(
            "Labels mapping",
            '{\n  "bell": "bell",\n  "morse": "morse"\n}',
            height=100,
            key="lbl_a",
        )

        st.markdown("**Audio Source URLs (one per line)**")
        audio_urls_input = st.text_area(
            "URLs",
            "https://soundcamp.org/sounds/382/RECEPTION_BELL_oVn.wav\nhttps://soundcamp.org/sounds/382/morse_code_oscillator_-_medium_pitched_PTv.wav",
            height=100,
        )
        truths_input_a = st.text_input(
            "Ground Truth Labels (Indices for Training)", "0, 1", key="tr_a"
        )

        run_audio = st.button("🚀 Run Audio Pipelines", type="primary")

    with col2:
        st.subheader("Execution & Results")
        if run_audio:
            with st.spinner(
                "Downloading audio clips and processing pipeline..."
            ):
                try:
                    label_verbalizations = json.loads(labels_input_a)
                    urls = [
                        u.strip()
                        for u in audio_urls_input.split("\n")
                        if u.strip()
                    ]
                    truths = [
                        int(x.strip()) for x in truths_input_a.split(",")
                    ]

                    audios = []
                    for url in urls:
                        content = requests.get(url).content
                        audios.append(content)

                    st.markdown("### 🔊 Input Preview")
                    for idx, audio_bytes in enumerate(audios):
                        st.text(f"Audio Index {idx}")
                        st.audio(audio_bytes, format="audio/wav")

                    pipeline = AudioPipeline(
                        encoder_name_a,
                        encoder_class_a,
                        label_verbalizations,
                        prompt_template_a,
                    )

                    # Pathway A: Zero-Shot
                    st.markdown("### 🎛️ Pathway A: Zero-Shot Predictions")
                    st.caption(
                        "Evaluating the model out-of-the-box without any additional training."
                    )
                    preds_zero = pipeline.predict(audios, batch_size=8)
                    for idx, pred in enumerate(preds_zero):
                        st.info(f"**Audio {idx}** ➔ **Prediction:** `{pred}`")

                    st.write("---")

                    # Pathway B: Label-Tuning
                    st.markdown("### 🏋️ Pathway B: Label-Tuning Fine-Tuning")
                    st.caption(
                        "Adapting the model's classification space using your provided ground truths."
                    )

                    with st.status(
                        "Training via label-tuning...", expanded=True
                    ) as status:
                        pipeline.fit(audios, truths)
                        status.update(
                            label="Fine-tuning complete!",
                            state="complete",
                            expanded=False,
                        )

                    preds_post = pipeline.predict(audios, batch_size=8)
                    for idx, pred in enumerate(preds_post):
                        st.success(
                            f"**Audio {idx}** ➔ **Post-Training Prediction:** `{pred}`"
                        )

                    try:
                        del audios
                        del preds_zero
                        del preds_post
                        gc.collect()
                    except Exception:
                        pass
                except Exception as e:
                    st.error(f"An error occurred: {e}")
        else:
            st.info(
                "Configure the options on the left and click 'Run Audio Pipelines'."
            )

# -----------------------------------------------------------------------------
# Tab 4: Video Classification
# -----------------------------------------------------------------------------
with tab_video:
    st.header("Video Classification")

    col1, col2 = st.columns([1, 2], gap="large")

    with col1:
        st.subheader("Configuration")
        encoder_name_v = st.text_input(
            "Encoder Name",
            "microsoft/xclip-base-patch16-zero-shot",
            key="en_v",
            disabled=True,
        )
        encoder_class_v = st.text_input(
            "Encoder Class", "xclip", key="ec_v", disabled=True
        )
        prompt_template_v = st.text_input(
            "Prompt Template", "The video shows a {}", key="pt_v"
        )

        st.markdown("**Label Verbalizations (JSON format)**")
        labels_input_v = st.text_area(
            "Labels mapping",
            '{"programming": "programming course",\n "anime": "anime tv show",\n "french song": "french song"}',
            #'{\n  "programming": "programming course",\n  "spaghetti": "man eating spaghetti",\n  "dog": "brown dog",\n  "penguin": "a penguin",\n  "song": "a french song"\n}',
            height=150,
            key="lbl_v",
        )

        st.markdown("**YouTube Source URLs (one per line)**")
        video_urls_input = st.text_area(
            "URLs",
            "https://www.youtube.com/watch?v=R2mO_XFiXKc\nhttps://www.youtube.com/watch?v=LpNVf8sczqU",
            height=100,
            key="url_v",
        )
        truths_input_v = st.text_input(
            "Ground Truth Labels (Indices for Training)", "1, 2", key="tr_v"
        )

        run_video = st.button("🚀 Run Video Pipelines", type="primary")

    with col2:
        st.subheader("Execution & Results")
        if run_video:
            with st.spinner(
                "Downloading video clips via yt-dlp and processing pipeline..."
            ):
                try:
                    label_verbalizations = json.loads(labels_input_v)
                    urls = [
                        u.strip()
                        for u in video_urls_input.split("\n")
                        if u.strip()
                    ]
                    truths = [
                        int(x.strip()) for x in truths_input_v.split(",")
                    ]

                    videos = []
                    for url in urls:
                        video_bytes = download_youtube_video(url)
                        videos.append(video_bytes)

                    st.markdown("### 📹 Input Preview")
                    grid = st.columns(len(videos))
                    for idx, video_bytes in enumerate(videos):
                        grid[idx].text(f"Video Index {idx}")
                        grid[idx].video(video_bytes, format="video/mp4")

                    pipeline = VideoPipeline(
                        encoder_name_v,
                        encoder_class_v,
                        label_verbalizations,
                        prompt_template_v,
                    )

                    # Pathway A: Zero-Shot
                    st.markdown("### 🎛️ Pathway A: Zero-Shot Predictions")
                    st.caption(
                        "Evaluating the model out-of-the-box without any additional training."
                    )
                    preds_zero = pipeline.predict(videos, batch_size=8)
                    for idx, pred in enumerate(preds_zero):
                        st.info(f"**Video {idx}** ➔ **Prediction:** `{pred}`")

                    st.write("---")

                    # Pathway B: Label-Tuning
                    st.markdown("### 🏋️ Pathway B: Label-Tuning Fine-Tuning")
                    st.caption(
                        "Adapting the model's classification space using your provided ground truths."
                    )

                    with st.status(
                        "Training via label-tuning...", expanded=True
                    ) as status:
                        pipeline.fit(videos, truths)
                        status.update(
                            label="Fine-tuning complete!",
                            state="complete",
                            expanded=False,
                        )

                    preds_post = pipeline.predict(videos, batch_size=8)
                    for idx, pred in enumerate(preds_post):
                        st.success(
                            f"**Video {idx}** ➔ **Post-Training Prediction:** `{pred}`"
                        )

                    try:
                        del videos
                        del preds_zero
                        del preds_post
                        gc.collect()
                    except Exception:
                        pass
                except Exception as e:
                    st.error(f"An error occurred: {e}")
        else:
            st.info(
                "Configure the options on the left and click 'Run Video Pipelines'."
            )
